[package]
name = "atuin"
version = "0.1.1"
authors = ["Ellie Huxtable <e@elm.sh>"]
edition = "2018"
license = "MIT"
description = "atuin - sync your shell history"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
chrono = "0.4.19"
eyre = "0.6.1"
shellexpand = "2.0.0"
structopt = "0.3.15"
directories = "3.0.1"

[dependencies.rusqlite]
version = "0.24.0"
features = ["bundled"]
